genericcrud/urls.py
from django.conf.urls import url
from django.contrib import admin
from books import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/$', views.BookListView.as_view(), name='book_list'),
    url(r'^home/$', views.BookListView.as_view(), name='home'),
    url(r'^books/(?P<pk>\d+)/$', views.BookDetailView.as_view(),
        name='book_detail'),
    url(r'^books/(?P<pk>\d+)/update/$', views.BookUpdateView.as_view(),
        name='book_update'),
    url(r'^create/$', views.BookCreateView.as_view(),
        name='book_create'),
    url(r'^books/add_publisher/$',
        views.PublisherCreateView.as_view(), name='add_publisher'),
    url(r'^books/add_author/$',
        views.AuthorCreateView.as_view(), name='add_author'),
    url(r'^add_type/$', views.NetworkDeviceTypeCreateView.as_view(), name='add_type'),
    url(r'^add_category/$', views.NetworkDeviceCategoryCreateView.as_view(),
        name='add_category'),
    url(r'^load_type/$', views.get_type_by_category,
        name='load_types')
]

books/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Author(models.Model):
    first_name = models.CharField(max_length=500,
                                  db_index=True,
                                  verbose_name=u'имя')
    last_name = models.CharField(max_length=500,
                                 db_index=True,
                                 verbose_name=u'фамилия')

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)

    class Meta:
        verbose_name = u'автор'


class Publisher(models.Model):
    name = models.CharField(max_length=500,
                            db_index=True,
                            verbose_name=u'название издательства')
    address = models.CharField(max_length=500,
                               verbose_name=u'адрес издательства')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'издательство'


class NetworkDeviceCategory(models.Model):
    name = models.CharField(max_length=500,
                            db_index=True,
                            verbose_name='категория устройства')
    comment = models.CharField(max_length=500,
                               verbose_name='комментарий')

    def __str__(self):
        return self.name


class NetworkDeviceType(models.Model):
    name = models.CharField(max_length=500,
                            db_index=True,
                            verbose_name='тип устройства')
    category = models.ForeignKey(NetworkDeviceCategory,
                                 verbose_name='категрия устройства',
                                 on_delete=models.CASCADE)
    comment = models.CharField(max_length=500,
                               verbose_name='комментарий')

    def __str__(self):
        return self.name


class Books(models.Model):
    title = models.CharField(max_length=500,
                             db_index=True,
                             verbose_name=u'название книги')
    authors = models.ManyToManyField(Author,
                                     verbose_name=u'авторы')
    publisher = models.ForeignKey(Publisher,
                                  verbose_name=u'издательство',
                                  on_delete=models.CASCADE)
    manually_set_type = models.ForeignKey(NetworkDeviceType,
                                          on_delete=models.CASCADE,
                                          blank=True,
                                          null=True)

    class Meta:
        verbose_name = u'книга'

books/forms.py
from django import forms
from django.forms import widgets
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.contrib.staticfiles.templatetags import staticfiles

from .models import Books, Publisher, Author, NetworkDeviceType, NetworkDeviceCategory


class RelatedFieldWidgetCanAdd(widgets.Select):
    def __init__(self, related_model, related_url=None, *args, **kw):
        super(RelatedFieldWidgetCanAdd, self).__init__(*args, **kw)

        if not related_url:
            rel_to = related_model
            info = (rel_to._meta.app_label, rel_to._meta.object_name.lower())
            related_url = 'admin:%s_%s_add' % info

        # Be careful that here "reverse" is not allowed
        self.related_url = related_url

    def render(self, name, value, *args, **kwargs):
        self.related_url = reverse(self.related_url)
        output = list()
        output.append(super(RelatedFieldWidgetCanAdd, self).render(
            name, value, *args, **kwargs))
        output.append(
            u'<a href="%s" id="add_id_%s"><img src="%s" alt="My image"/>Добавить</a>' %
            (self.related_url, name, staticfiles.static('books/img/icon-addlink.svg'))
        )
        return mark_safe(u''.join(output))


class RelatedFieldWidgetCanAddMultiple(widgets.SelectMultiple):
    def __init__(self, related_model, related_url=None, *args, **kw):
        super(RelatedFieldWidgetCanAddMultiple, self).__init__(*args, **kw)

        if not related_url:
            rel_to = related_model
            info = (rel_to._meta.app_label, rel_to._meta.object_name.lower())
            related_url = 'admin:%s_%s_add' % info

        # Be careful that here "reverse" is not allowed
        self.related_url = related_url

    def render(self, name, value, *args, **kwargs):
        self.related_url = reverse(self.related_url)
        output = list()
        output.append(super(RelatedFieldWidgetCanAddMultiple, self).render(
            name, value, *args, **kwargs))
        output.append(
            u'<a href="%s" id="add_id_%s"><img src="%s" alt="My image"/>Добавить</a>' %
            (self.related_url, name, staticfiles.static('books/img/icon-addlink.svg'))
        )
        return mark_safe(u''.join(output))


class BookForm(forms.ModelForm):
    authors = forms.ModelMultipleChoiceField(
        queryset=Author.objects.all(),
        widget=RelatedFieldWidgetCanAddMultiple(Author,
                                                related_url='add_author'),
        label='Авторы'
    )
    publisher = forms.ModelChoiceField(
        queryset=Publisher.objects.all(),
        widget=RelatedFieldWidgetCanAdd(Publisher,
                                        related_url='add_publisher'),
        label='Издательство'
    )
    category = forms.ModelChoiceField(
        queryset=NetworkDeviceCategory.objects.all(),
        widget=RelatedFieldWidgetCanAdd(NetworkDeviceCategory,
                                        related_url='add_category'),
        label='Категория'
    )
    manually_set_type = forms.ModelChoiceField(
        queryset=NetworkDeviceType.objects.none(),
        widget=RelatedFieldWidgetCanAdd(
            NetworkDeviceType,
            related_url='add_type'
        ),
        label='Тип'
    )

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)

        if 'category' in self.data:
            try:
                category = int(self.data.get('category'))
                self.fields['manually_set_type'].queryset = (
                    NetworkDeviceType.objects.filter(category=category))
            except (ValueError, TypeError):
                pass  # invalid input from the client, ignore

    class Meta:
        model = Books
        fields = ('title', 'authors', 'publisher',
                  'category', 'manually_set_type')

books/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy

from .models import Books, Publisher, Author, NetworkDeviceCategory, NetworkDeviceType
from .forms import BookForm


class BookListView(ListView):
    model = Books


class BookDetailView(DetailView):
    model = Books


class BookCreateView(CreateView):
    model = Books
    # fields = ('title', 'authors', 'publisher')
    form_class = BookForm
    success_url = reverse_lazy('book_list')


class BookUpdateView(UpdateView):
    model = Books
    form_class = BookForm
    # fields = ('title', 'authors', 'publisher')

    def get_success_url(self):
        return reverse_lazy('book_detail', kwargs={'pk': self.kwargs['pk']})


class PublisherCreateView(CreateView):
    model = Publisher
    fields = ('name', 'address')
    success_url = reverse_lazy('book_list')


class AuthorCreateView(CreateView):
    model = Author
    fields = ('first_name', 'last_name')
    success_url = reverse_lazy('book_list')


class NetworkDeviceTypeCreateView(CreateView):
    model = NetworkDeviceType
    fields = ('name', 'category', 'comment')
    success_url = reverse_lazy('book_list')


class NetworkDeviceCategoryCreateView(CreateView):
    model = NetworkDeviceCategory
    fields = ('name', 'comment')
    success_url = reverse_lazy('book_list')


def get_type_by_category(request):
    category = request.GET.get('category')
    types = NetworkDeviceType.objects.filter(category=category)
    return render(request, 'books/types_dropdown.html', {'types': types})

books/templates/books/author_form.html
{% extends 'base.html' %}

{% load static %}

{% block javascript %}

{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Books</a></li>

  <li class="breadcrumb-item active">Create author</li>
{% endblock %}

{% block content %}

<h2>Добавить автора</h2>
<form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/bs_form.html' with form=form %}
    <button type="submit">Save</button>
    <a href="{% url 'book_list' %}">Cancel</a>
</form>
{% endblock %}

books/templates/books/books_detail.html
{% extends 'base.html' %}

{% load static %}

{% block javascript %}

{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'home' %}">Books</a></li>
<li class="breadcrumb-item active">{{ object.title }}</li>
{% endblock %}

{% block content %}

<h2>{{object.title}}</h2>
<table class="table">
    <tbody>
    <tr>
        <td>Авторы</td>
        <td>
            <table>
                {% for author in object.authors.all %}
                <tr>
                    <td>{{author}}</td>
                </tr>
                {% endfor %}
            </table>
        </td>
    </tr>
    <tr>
        <td>Издательство</td>
        <td>{{object.publisher.name}}</td>
    </tr>
    </tbody>
</table>
<a href="{% url 'book_update' object.pk %}">Редактировать</a>
{% endblock %}

books/templates/books/books_form.html
{% extends 'base.html' %}

{% load static %}

{% block javascript %}

{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'home' %}">Books</a></li>
{% if form.instance.pk %}
<li class="breadcrumb-item"><a href="{% url 'book_detail' form.instance.pk %}">{{form.instance.title}}</a></li>
{% endif %}
{% if form.instance.pk %}
<li class="breadcrumb-item active">Edit book</li>
{% else %}
<li class="breadcrumb-item active">Create book</li>
{% endif %}
{% endblock %}

{% block content %}

<h2>Добавить книгу</h2>
<form method="post"
      data-url="{% url 'load_types' %}"
      novalidate id="node_form">
    {% csrf_token %}
    {% include 'includes/bs_form.html' with form=form %}
    <button type="submit">Сохранить</button>
    <a href="{% url 'book_list' %}">Отменить</a>
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_category").change(function () {
      var url = $("#node_form").attr("data-url");
      var category = $(this).val();

      $.ajax({                       // initialize an AJAX request
        url: url,
        data: {
          'category': category
        },
        success: function (data) {   // `data` is the return of the `load_types` view function
          $("#id_manually_set_type").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });

</script>
{% endblock %}

books/templates/books/books_list.html
{% extends 'base.html' %}

{% load static %}

{% block javascript %}

{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item active">Books</li>
{% endblock %}

{% block content %}
<h1 class="page-header">Books</h1>

<a href="{% url 'book_create' %}">New book</a>

<table class="table" id="book-table">
    <thead>
    <tr>
        <th>#</th>
        <th>Название</th>
        <th>Авторы</th>
        <th>Издательство</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% include 'books/includes/partial_book_list.html' %}
    </tbody>
</table>

{% endblock %}

books/templates/books/networkdevicecategory_form.html
{% extends 'base.html' %}

{% load static %}

{% block javascript %}

{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Books</a></li>

  <li class="breadcrumb-item active">Добавить категорию</li>
{% endblock %}

{% block content %}

<h2>Добавить категорию</h2>
<form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/bs_form.html' with form=form %}
    <button type="submit">Сохранить</button>
    <a href="{% url 'book_list' %}">Отменить</a>
</form>
{% endblock %}

books/templates/books/networkdevicetype_form.html
{% extends 'base.html' %}

{% load static %}

{% block javascript %}

{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Books</a></li>

  <li class="breadcrumb-item active">Добавить тип</li>
{% endblock %}

{% block content %}

<h2>Добавить тип</h2>
<form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/bs_form.html' with form=form %}
    <button type="submit">Сохранить</button>
    <a href="{% url 'book_list' %}">Отменить</a>
</form>
{% endblock %}

books/templates/books/publisher_form.html
{% extends 'base.html' %}

{% load static %}

{% block javascript %}

{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Books</a></li>

  <li class="breadcrumb-item active">Create publisher</li>
{% endblock %}

{% block content %}

<h2>Добавить издательство</h2>
<form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/bs_form.html' with form=form %}
    <button type="submit">Сохранить</button>
    <a href="{% url 'book_list' %}">Отменить</a>
</form>
{% endblock %}

books/templates/books/types_dropdown.html
<option value="">---------</option>
{% for type in types %}
<option value="{{ type.pk }}">{{ type.name }}</option>
{% endfor %}